name: 01 - Create Simple Workflow

on:
  - push
  - workflow_dispatch

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World"

      - name: Run multiline commands
        run: |
          pwd
          python --version

      - name: Run Python command
        shell: python
        run: |
          import platform 
          print(platform.python_version())

  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Run Powershell command
        run: Get-Location
