name: 04 - Trigger Workflows with Events

on:
  push:
    branches:
      - 04-**
  pull_request:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World!"
