name: 04 - Trigger Workflows with Events

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World!"

      - name: Run multiline commands
        run: |
          pwd
          python --version

      - name: Run Python command
        shell: python
        run: |
          import platform 
          print(platform.python_version())
