name: 07 - Use Workflow Matrices

on:
  workflow_dispatch:
    inputs:
      job:
        type: choice
        options:
          - 1D_Matrix
          - 2D_Matrix

jobs:
  one-dimension-matrix:
    name: Java ${{ matrix.version }}
    if: ${{ inputs.job == '1D_Matrix' }}
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}

      - name: Check Java version
        run: java -version

  two-dimension-matrix:
    name: ${{ matrix.os }} - Java ${{ matrix.version }}
    if: ${{ inputs.job == '2D_Matrix' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.version }}

      - name: Check Java version
        run: java -version
